from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication,QWidget,QPushButton, QLabel, QVBoxLayout,QHBoxLayout,QMessageBox,QRadioButton
def show_win():
    v=QMessageBox()
    v.setText("Вірно!\nВи виграли гіроскутер")
    v.exec_()
def show_lose():
    v=QMessageBox()
    v.setText("Ні,2015 року\nВи виграли фірмовий плакат")
    v.exec_()
app=QApplication([])
main_win=QWidget()
main_win.setWindowTitle("Конкурс від Crazy People")
main_win.resize(400,200)
q=QLabel("В якому році канал отримав золоту кнопку від YouTube?")
a1=QRadioButton("2005")
a2=QRadioButton("2010")
a3=QRadioButton("2015")
a4=QRadioButton("2020")
hh=QVBoxLayout()
h1=QHBoxLayout()
h2=QHBoxLayout()
h3=QHBoxLayout()
h1.addWidget(q,alignment = Qt.AlignCenter)
h2.addWidget(a1,alignment = Qt.AlignCenter)
h2.addWidget(a2,alignment = Qt.AlignCenter)
h3.addWidget(a3,alignment = Qt.AlignCenter)
h3.addWidget(a4,alignment = Qt.AlignCenter)
hh.addLayout(h1)
hh.addLayout(h2)
hh.addLayout(h3)
main_win.setLayout(hh)
a1.clicked.connect(show_lose)
a2.clicked.connect(show_lose)
a3.clicked.connect(show_win)
a4.clicked.connect(show_lose)
main_win.show()
app.exec_()
